import Head from 'next/head'
import Image from 'next/image'
import Logo from '../../public/Logo_Final.png'
import perfil from '../../public/perfil.jpg'
import { Inter } from '@next/font/google'
import Inicio from 'components/ Inicio'
import Nav from 'components/Nav'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Audio Sul de Minas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <header>
          <div className="flex flex-row justify-center  lg:justify-between p-2 bg-gradient-to-t from-slate-100 to-slate-400 drop-shadow-dark1">
            <div className="hidden lg:block border-b border-solid border-slate-400 w-1/4 mx-20 mt-10 text-slate-700">
              <p>Informações de teste </p>
              <p>Av Damião Junqueira de Souza</p>
            </div>
            <div className='flex'>
              <Image src={Logo} alt="logo da empresa"
                className="w-80 drop-shadow-dark "
              />
            </div>
            <div className=" hidden lg:block text-end border-b border-solid border-slate-400 w-1/4 pb-1 mx-20 mt-10  text-slate-700">
              <p>35 988454245</p>
              <p>Localidade</p>
            </div>
          </div>
          <Nav />
        </header>
        <Inicio />
        <div className="p-16 flex flex-col justify-center items-center ">
          <h2 className="text-slate-700 text-2xl font-bold p-5">
            Algum testo aleatório
          </h2>
          <p className="p-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos at blanditiis itaque laboriosam cumque dolor harum mollitia tenetur est, eligendi aut sapiente molestias quas maiores fuga odio corporis adipisci reprehenderit!</p>
          <button className="bg-slate-600 rounded-2xl px-4  border-double border-4 border-slate-300 text-white ">Learn More</button>
        </div>
        <div>
          <div className="flex flex-col justify-center items-center md:grid md:grid-cols-2  bg-slate-700">
            <div className="flex justify-end p-16">
              <Image src={perfil} alt="imagen de perfil de um médico"
                className="w-44 border-double border-4 border-slate-300"
              />
            </div>
            <div className="p-2 md:pt-16 pb-10 md:pr-20 flex flex-col justify-center items-center">
              <h2 className="text-white text-2xl">Médico xyz </h2>
              <p className="text-white my-10">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Saepe accusamus maxime, reprehenderit impedit est aspernatur officiis quaerat porro nisi nihil quas consequuntur necessitatibus. Animi impedit ipsum cumque, commodi iure id.
              </p>
              <button className="bg-slate-600 rounded-2xl px-4  border-double border-4 border-slate-300 text-white ">Learn More</button>
            </div>
          </div>
        </div>

        <div>
          <div className="px-20">
            <h2 className='text-slate-700 font-bold text-2xl flex p-5 pt-20 justify-center items-center border-b-2 border-slate-700 '>Conheça nossa equipe</h2>
          </div>

          <div className='px-20 md:flex justify-center items-center'>
            <div className="p-5 w-52">
              <div className=" bg-slate-300 p-2 flex flex-col justify-center items-center border-double border-4 border-slate-700">
                <Image src={perfil} alt="foto de perfil do médico"
                  className="w-44"
                />
                <h2 className="text-slate-700 font-bold">Nome</h2>
                <p className="text-slate-700 font-bold">Função</p>
                <button className="bg-slate-600 rounded-2xl px-4  border-double border-4 border-slate-300 text-white ">Learn More</button>
              </div>
            </div>
            <div className="p-5 w-52">
              <div className=" bg-slate-300 p-2 flex flex-col justify-center items-center border-double border-4 border-slate-700">
                <Image src={perfil} alt="foto de perfil do médico"
                  className="w-44"
                />
                <h2 className="text-slate-700 font-bold">Nome</h2>
                <p className="text-slate-700 font-bold">Função</p>
                <button className="bg-slate-600 rounded-2xl px-4  border-double border-4 border-slate-300 text-white ">Learn More</button>
              </div>
            </div>
            <div className="p-5 w-52">
              <div className=" bg-slate-300 p-2 flex flex-col justify-center items-center border-double border-4 border-slate-700">
                <Image src={perfil} alt="foto de perfil do médico"
                  className="w-44"
                />
                <h2 className="text-slate-700 font-bold">Nome</h2>
                <p className="text-slate-700 font-bold">Função</p>
                <button className="bg-slate-600 rounded-2xl px-4  border-double border-4 border-slate-300 text-white ">Learn More</button>
              </div>
            </div>
            <div className="p-5 w-52">
              <div className=" bg-slate-300 p-2 flex flex-col justify-center items-center border-double border-4 border-slate-700">
                <Image src={perfil} alt="foto de perfil do médico"
                  className="w-44"
                />
                <h2 className="text-slate-700 font-bold">Nome</h2>
                <p className="text-slate-700 font-bold">Função</p>
                <button className="bg-slate-600 rounded-2xl px-4  border-double border-4 border-slate-300 text-white ">Learn More</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
