import Head from 'next/head'
import Image from 'next/image'
import Ana from '../../public/Ana.jpeg'
import Priscila2 from '../../public/Priscila2.jpeg'
import image4 from '../../public/4.jpeg'
import { Inter } from '@next/font/google'
import Inicio from 'components/ Inicio'
import Nav from 'components/Nav'
import Nav1 from 'components/Nav1'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import argosy from "../../public/patrocinador/argosy.jpeg"
import oticon from "../../public/patrocinador/oticon.jpeg"
import phonak from "../../public/patrocinador/phonak.jpeg"
import rexton from "../../public/patrocinador/rexton.jpeg"
import starkey from "../../public/patrocinador/starkey.jpeg"

import { faArrowAltCircleRight,faTrademark } from '@fortawesome/free-solid-svg-icons'

import Card from 'components/Card'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const data = new Date();
  const ano = data.getFullYear();
  return (
    <>
      <Head>
        <title>Audio Sul de Minas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <header>
          <Nav1 />
          <Nav />
        </header>
        <Inicio />
        <div className='bg-slate-200 flex flex-col lg:flex-row justify-around'>
          <div className='p-10 lg:pt-16 lg:pb-16 lg:pl-16 lg:p-0 lg:w-1/2 flex flex-col '>
            <h2 className='border-b border-tema-site w-full mb-5 text-tema-site text-xl font-bold pb-2'>
              Quem somos
            </h2>
            <p className='text-justify'>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores dolorum numquam officiis nihil, quia repellendus illum qui, labore modi natus ratione officia? Ex ea maxime assumenda sunt? Architecto, quam et! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora neque maiores natus odit odio eos, dolorum sapiente laboriosam eius vel. Neque nihil fuga sunt obcaecati nulla illo explicabo, nemo possimus.lore
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores dolorum numquam officiis nihil, quia repellendus illum qui, labore modi natus ratione officia? Ex ea maxime assumenda sunt? Architecto, quam et! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora neque maiores natus odit odio eos, dolorum sapiente laboriosam eius vel. Neque nihil fuga sunt obcaecati nulla illo explicabo, nemo possimus.lore
            </p>
          </div>
          <div className="p-16 flex text-center md:text-start flex-col">
            <h2 className='border-b border-tema-site w-full mb-5 text-tema-site text-xl font-bold pb-2'>
              Colaboradores
            </h2>
            <div className='flex flex-col lg:flex-row gap-5 justify-center items-center text-center'>
              <div>
                <div className='rounded-3xl border-2 border-tema-site w-[266px] h-[300px] flex justify-center items-center'>
                  <Image src={Priscila2} alt="imagen de perfil de um médico"
                    className="w-64 h-[290px] border-double border-4 border-branco rounded-3xl"
                  />
                </div>
                <h2 className='text-xl text-tema-site font-bold'>
                  Priscila Guimarães
                </h2>
                <p>Fonoaudióloga Audiologista</p>
              </div>
              <div>
                <div className='rounded-3xl border-2 border-tema-site w-[266px] h-[300px] flex justify-center items-center'>
                  <Image src={Ana} alt="foto de perfil do médico"
                    className="w-64 h-[290px] border-double border-4 border-branco rounded-3xl" />
                </div>
                <h2 className='text-xl text-tema-site font-bold'>
                  Ana Carolina Mazulka
                </h2>
                <p>Fonoaudióloga Audiologista</p>
              </div>
            </div>
          </div>
        </div>

        <div className='pt-10 flex flex-col justify-center items-center'>
          <h2 className='text-tema-site text-2xl border-b border-tema-site text-center font-bold pb-2'>
            Serviços
          </h2>
          <p className='p-2 text-center font-bold'>
            Confira todos os serviços que executamos em nossa clínica.
          </p>
          <div className='flex flex-col lg:flex-row justify-center items-center lg:items-start p-16 w-full lg:gap-52'>
            <div>
              <h2 className='text-lg font-bold pb-5'>
                O que fazemos?
              </h2>
              <ul className='text-tema-site'>
                <li className='flex gap-2 pb-2'>
                  <FontAwesomeIcon icon={faArrowAltCircleRight} width={15}
                    className="text-tema-site"
                  />
                  Seleção e adaptação de aparelhos auditivos
                </li>
                <li className='flex gap-2 pb-2'>
                  <FontAwesomeIcon icon={faArrowAltCircleRight} width={15}
                    className="text-tema-site"
                  />
                  Orientação e acompanhamento pós adaptação
                </li>
                <li className='flex gap-2 pb-2'>
                  <FontAwesomeIcon icon={faArrowAltCircleRight} width={15}
                    className="text-tema-site"
                  />
                  Assistência técnica de aparelhos auditivos em geral</li>
                <li className='flex gap-2 pb-2'>
                  <FontAwesomeIcon icon={faArrowAltCircleRight} width={15}
                    className="text-tema-site"
                  />
                  Vendas de acessórios, como pilhas e umidificadores
                </li>
                <li className='flex gap-2 pb-2'>
                  <FontAwesomeIcon icon={faArrowAltCircleRight} width={15}
                    className="text-tema-site"
                  />
                  Aparelhos e confecção de moldes em laboratório
                </li>
                <li className='flex gap-2 pb-2'>
                  <FontAwesomeIcon icon={faArrowAltCircleRight} width={15}
                    className="text-tema-site"
                  />
                  Acompanhamento no processo de adaptação
                </li>
              </ul>
            </div>
            <div className='rounded-3xl border-2 border-tema-site w-[266px] h-[270px] flex justify-center items-center'>
              <Image src={image4}
                className="w-64 h-[260px] border-double border-4 border-branco rounded-3xl"
              />

            </div>
          </div>
        </div>
        <div className='bg-slate-200 pt-10 flex flex-col justify-center items-center '>
          <div className='flex flex-col w-full justify-center items-center'>
            <h2 className='text-tema-site text-2xl border-b border-tema-site text-center font-bold pb-2'>
              Produtos
            </h2>
            <p className='p-2 text-center font-bold'>
              Temos os melhores produtos para auxiliar no seu tratamento
            </p>
          </div>
          <div className='p-16 grid lg:grid-cols-4 justify-center items-center gap-5 lg:w-[1000px]'>
            <Card
              title='CIC ou Micro Canal'
              content='Lorem ipsum dolor sit amet consectetur,' 
            />

            <Card
              title='ITC ou Intra Canal'
              content='Lorem ipsum dolor sit amet consectetur,'
            />
            <Card
              title='Micro BTE ou BTE'
              content='Lorem ipsum dolor sit amet consectetur,'
            />
            <Card
              title='Open Fit'
              content='Lorem ipsum dolor sit amet consectetur,'
            />
            <Card
              title='Retroauricular'
              content='Lorem ipsum dolor sit amet consectetur,'
            />
            <Card
              title='Desumidificador'
              content='Lorem ipsum dolor sit amet consectetur,'
            />
            <Card
              title='Outro Produto'
              content='Lorem ipsum dolor sit amet consectetur,'
            />
            <Card
              title='Pilhas (ou baterias)'
              content='Lorem ipsum dolor sit amet consectetur,'
            />
          </div>

        </div>
        <div className='flex flex-col justify-center items-center pt-10 px-5'>
          <h2 className='text-tema-site text-2xl border-b border-tema-site text-center font-bold pb-2'>
            Onde estamos
          </h2>
          <p className='p-2 text-center font-bold'>
            Estamos localizados no Centro de São Lourencço - Minas Gereais.
          </p>

          <p className='pt-5 text-center'>
            Av. Antônio Junqueira de Souza, 524 - Centro, São Lourenço - MG, 37470-000.
          </p>
          <p className='text-center'><b>Atendimento: </b>de segunda a sexta das 09:00 às 18:00.</p>
          <p className='text-center'><b>Telefones: </b> (35)3332-3972 - 98825-0742(WhatsApp).
          </p>
          <p className='text-center'><b>E-mail: </b>contato@audiosuldeminas.com.br</p>
        </div>
        <div className='w-screen flex flex-col  justify-center items-center pt-5'>
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d346.1291334886274!2d-45.05481063750276!3d-22.117748345847446!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94cb4b93690fc911%3A0xa55df95897731891!2sAv.%20Ant%C3%B4nio%20Junqueira%20de%20Souza%2C%20524%20-%20Centro%2C%20S%C3%A3o%20Louren%C3%A7o%20-%20MG%2C%2037470-000!5e0!3m2!1spt-BR!2sbr!4v1674233234286!5m2!1spt-BR!2sbr" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" className='w-screen md:w-screen  h-96 border-double border-4 border-tema-site '>
          </iframe>

          <div className='bg-slate-200 flex flex-col justify-center items-center pt-10 px-5 w-screen'>
            <h2 className='text-tema-site text-2xl border-b border-tema-site text-center font-bold pb-2'>
              Parceiros
            </h2>
            <p className='p-2 text-center font-bold'>
              As melhores marcas do mundo estão em nossa clinica
            </p>
            <div className='flex  lg:flex flex-wrap justify-center lg:w-[800px] gap-9 p-16'>
              <Image src={argosy} className='w-48 h-28' />
              <Image src={oticon} className='w-48 h-28' />
              <Image src={phonak} className='w-48 h-28' />
              <Image src={rexton} className='w-48 h-28' />
              <Image src={starkey} className='w-48 h-28' />
            </div>

            <footer className='bg-tema-site text-branco w-screen flex flex-col justify-center text-center p-5'>
              <p>{ano},Áudio Sul de Minas - Todos os Direitos Reservados</p>
              <p>Developed by Rixxer &trade;</p>
              
            </footer>
          </div>
        </div>
      </div>
    </>
  )
}
